import * as React from "react";
import { Image, StyleSheet, Text, View } from "react-native";
import { FontSize, Color, FontFamily, Border } from "../GlobalStyles";

const HomeScreen = () => {
  return (
    <View style={styles.container}>
      <Text>Home Screen</Text>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#8fcbbc'
  },
  footerLayout: {
    width: 431,
    position: "absolute",
  },
  textTypo6: {
    fontSize: FontSize.size_xs,
    textAlign: "left",
    color: Color.colorBlack,
    fontFamily: FontFamily.openSansHebrew,
  },
  text2Position: {
    left: 113,
    position: "absolute",
  },
  textTypo5: {
    transform: [
      {
        rotate: "180deg",
      },
    ],
    fontFamily: FontFamily.fontAwesome6Pro,
    textAlign: "left",
  },
  textPosition10: {
    top: 17,
    position: "absolute",
  },
  questionChildLayout: {
    height: 53,
    width: 395,
    position: "absolute",
  },
  childShadowBox1: {
    shadowOpacity: 1,
    elevation: 10,
    shadowRadius: 10,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowColor: "rgba(0, 0, 0, 0.05)",
    backgroundColor: Color.colorWhite,
    borderRadius: Border.br_8xs,
    top: 0,
    left: 0,
  },
  itemLayout: {
    height: 34,
    width: 34,
    position: "absolute",
  },
  questionLayout: {
    height: 172,
    width: 395,
    position: "absolute",
  },
  textTypo4: {
    textAlign: "right",
    fontFamily: FontFamily.openSansHebrew,
  },
  lineLayout: {
    width: 397,
    position: "absolute",
  },
  textLayout1: {
    height: 28,
    textAlign: "right",
  },
  salesLayout: {
    height: 378,
    width: 542,
    position: "absolute",
  },
  peopleLayout: {
    height: 35,
    width: 250,
    top: 343,
    position: "absolute",
  },
  pfofileLayout: {
    width: 35,
    height: 35,
    top: 0,
    position: "absolute",
  },
  peopleShadowBox: {
    elevation: 6,
    shadowRadius: 6,
    left: 63,
    width: 61,
    shadowColor: "rgba(0, 0, 0, 0.1)",
    borderRadius: Border.br_11xl,
    height: 35,
    shadowOpacity: 1,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    backgroundColor: Color.colorWhite,
    top: 0,
    position: "absolute",
  },
  textPosition7: {
    top: 8,
    position: "absolute",
  },
  productLayout1: {
    height: 265,
    position: "absolute",
  },
  starsLayout: {
    height: 30,
    position: "absolute",
  },
  textTypo3: {
    color: Color.colorGoldenrod,
    top: 3,
    transform: [
      {
        rotate: "180deg",
      },
    ],
    fontFamily: FontFamily.fontAwesome6Pro,
    textAlign: "left",
  },
  textPosition3: {
    left: 193,
    fontSize: FontSize.size_base,
    position: "absolute",
  },
  text70Position: {
    left: 146,
    position: "absolute",
  },
  productLayout: {
    width: 265,
    height: 265,
    position: "absolute",
  },
  textLayout: {
    width: 145,
    height: 28,
    textAlign: "right",
    color: Color.gray,
    fontSize: FontSize.size_lg,
    position: "absolute",
  },
  arrowsLayout1: {
    width: 67,
    height: 30,
    top: 0,
    position: "absolute",
  },
  arrowsLayout: {
    width: 30,
    height: 30,
    top: 0,
  },
  itemPosition: {
    left: 37,
    position: "absolute",
  },
  bannerLayout: {
    borderRadius: Border.br_3xs,
    height: 87,
    width: 395,
    top: 0,
    left: 0,
    position: "absolute",
  },
  textPosition9: {
    left: 30,
    position: "absolute",
  },
  productItemPosition: {
    height: 168,
    top: 47,
    position: "absolute",
  },
  maskGroupPosition: {
    height: 147,
    top: 0,
    position: "absolute",
  },
  productItemLayout: {
    height: 23,
    backgroundColor: Color.pink,
    top: 114,
    width: 42,
    borderRadius: Border.br_3xs,
    position: "absolute",
  },
  textPosition1: {
    top: 116,
    position: "absolute",
  },
  textTypo2: {
    top: 152,
    color: Color.gray,
    textAlign: "left",
    fontFamily: FontFamily.openSansHebrew,
    fontSize: FontSize.size_xs,
    position: "absolute",
  },
  itemChildLayout1: {
    height: 164,
    width: 190,
    position: "absolute",
  },
  childShadowBox: {
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: Color.colorWhite,
    borderStyle: "solid",
    borderRadius: Border.br_xl,
    shadowColor: "rgba(0, 0, 0, 0.1)",
    shadowOpacity: 1,
    elevation: 10,
    shadowRadius: 10,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    top: 0,
    left: 0,
  },
  textPosition: {
    right: 14,
    textAlign: "right",
    color: Color.gray,
    fontFamily: FontFamily.openSansHebrew,
    position: "absolute",
  },
  text72Position: {
    top: 5,
    position: "absolute",
  },
  itemChildLayout: {
    height: 251,
    width: 190,
    position: "absolute",
  },
  textTypo1: {
    height: 20,
    top: 8,
    textAlign: "right",
    color: Color.gray,
    fontSize: FontSize.size_sm,
    fontFamily: FontFamily.openSansHebrew,
    position: "absolute",
  },
  iconLayout: {
    height: 54,
    width: 54,
    top: 0,
    position: "absolute",
  },
  textTypo: {
    top: 26,
    height: 26,
    textAlign: "right",
    fontWeight: "700",
    color: Color.gray,
    fontSize: FontSize.size_lg,
    fontFamily: FontFamily.openSansHebrew,
  },
  text65Layout: {
    width: 150,
    position: "absolute",
  },
  searchLayout: {
    width: 394,
    height: 50,
    position: "absolute",
  },
  headerLayout: {
    height: 29,
    position: "absolute",
  },
  footerMenuChild: {
    top: 30,
    height: 64,
    left: 0,
  },
  text: {
    left: 24,
    textAlign: "left",
    color: Color.colorBlack,
    fontFamily: FontFamily.openSansHebrew,
    top: 67,
    fontSize: FontSize.size_xs,
    position: "absolute",
  },
  text1: {
    left: 341,
    textAlign: "left",
    color: Color.colorBlack,
    fontFamily: FontFamily.openSansHebrew,
    top: 67,
    fontSize: FontSize.size_xs,
    position: "absolute",
  },
  text2: {
    textAlign: "left",
    color: Color.colorBlack,
    fontFamily: FontFamily.openSansHebrew,
    fontSize: FontSize.size_xs,
    top: 67,
  },
  text3: {
    left: 266,
    textAlign: "left",
    color: Color.colorBlack,
    fontFamily: FontFamily.openSansHebrew,
    top: 67,
    fontSize: FontSize.size_xs,
    position: "absolute",
  },
  text4: {
    left: 51,
    color: Color.pink,
    fontWeight: "300",
    fontSize: FontSize.size_lg,
    top: 45,
    transform: [
      {
        rotate: "180deg",
      },
    ],
    position: "absolute",
  },
  text5: {
    left: 149,
    color: Color.pink,
    fontWeight: "300",
    fontSize: FontSize.size_lg,
    top: 45,
    transform: [
      {
        rotate: "180deg",
      },
    ],
    position: "absolute",
  },
  text6: {
    left: 295,
    color: Color.pink,
    fontWeight: "300",
    fontSize: FontSize.size_lg,
    top: 45,
    transform: [
      {
        rotate: "180deg",
      },
    ],
    position: "absolute",
  },
  text7: {
    left: 382,
    color: Color.pink,
    fontWeight: "300",
    fontSize: FontSize.size_lg,
    top: 45,
    transform: [
      {
        rotate: "180deg",
      },
    ],
    position: "absolute",
  },
  footerMenuItem: {
    marginLeft: -24.5,
    width: 50,
    height: 50,
    left: "50%",
    top: 0,
    position: "absolute",
  },
  text8: {
    marginLeft: 10.5,
    color: Color.colorWhite,
    left: "50%",
    transform: [
      {
        rotate: "180deg",
      },
    ],
    fontFamily: FontFamily.fontAwesome6Pro,
    textAlign: "left",
    fontWeight: "300",
    fontSize: FontSize.size_lg,
  },
  footerMenu: {
    top: 1885,
    left: -1,
    height: 94,
  },
  question4Child: {
    height: 53,
    width: 395,
    position: "absolute",
  },
  text9: {
    left: 112,
    color: Color.gray,
    fontSize: FontSize.size_sm,
    textAlign: "left",
    fontFamily: FontFamily.openSansHebrew,
  },
  question4Item: {
    left: 10,
    top: 10,
    width: 34,
  },
  text10: {
    left: 34,
    fontSize: FontSize.size_base,
    top: 19,
    transform: [
      {
        rotate: "180deg",
      },
    ],
    color: Color.pink,
    fontFamily: FontFamily.fontAwesome6Pro,
    textAlign: "left",
    position: "absolute",
  },
  question4: {
    top: 1813,
    left: 15,
  },
  questionAnswer3Child: {
    shadowOpacity: 1,
    elevation: 10,
    shadowRadius: 10,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowColor: "rgba(0, 0, 0, 0.05)",
    backgroundColor: Color.colorWhite,
    borderRadius: Border.br_8xs,
    top: 0,
    left: 0,
  },
  text11: {
    top: 18,
    left: 85,
    fontWeight: "700",
    fontSize: FontSize.size_sm,
    color: Color.pink,
    textAlign: "left",
    fontFamily: FontFamily.openSansHebrew,
    position: "absolute",
  },
  text12: {
    top: 57,
    lineHeight: 24,
    width: 352,
    height: 86,
    left: 30,
    position: "absolute",
    fontSize: FontSize.size_sm,
    color: Color.colorBlack,
  },
  questionAnswer3Item: {
    top: 11,
    left: 10,
  },
  text13: {
    top: 20,
    left: 33,
    fontSize: FontSize.size_base,
    color: Color.pink,
    position: "absolute",
  },
  questionAnswer3: {
    top: 1626,
    left: 15,
  },
  question2Child: {
    height: 53,
    width: 395,
    position: "absolute",
  },
  text14: {
    left: 108,
    width: 274,
    color: Color.gray,
    fontSize: FontSize.size_sm,
    top: 17,
    position: "absolute",
  },
  question2Item: {
    left: 11,
    top: 10,
    width: 34,
  },
  textPosition8: {
    width: 14,
    left: 35,
    fontSize: FontSize.size_base,
    top: 19,
    transform: [
      {
        rotate: "180deg",
      },
    ],
    color: Color.pink,
    fontFamily: FontFamily.fontAwesome6Pro,
    textAlign: "left",
    position: "absolute",
  },
  question2: {
    top: 1558,
    left: 15,
  },
  question1Child: {
    height: 53,
    width: 395,
    position: "absolute",
  },
  question1: {
    top: 1490,
    left: 15,
  },
  text19: {
    fontWeight: "700",
    fontFamily: FontFamily.openSansHebrew,
  },
  text20: {
    fontFamily: FontFamily.openSansHebrew,
  },
  text18: {
    left: 191,
    width: 205,
    color: Color.gray,
    top: 0,
    fontSize: FontSize.size_lg,
    position: "absolute",
  },
  line: {
    top: 38,
    backgroundColor: "#d9d9d9",
    height: 1,
    left: 0,
  },
  subHeader: {
    top: 1438,
    left: 13,
    height: 39,
  },
  pfofilePhotoHeader: {
    left: 215,
  },
  pfofilePhotoHeader2: {
    left: 173,
  },
  pfofilePhotoHeader3: {
    left: 132,
  },
  peopleBuyChild: {
    width: 61,
  },
  text21: {
    left: 79,
    fontWeight: "700",
    fontSize: FontSize.size_sm,
    textAlign: "left",
    color: Color.colorBlack,
    fontFamily: FontFamily.openSansHebrew,
  },
  text22: {
    top: 9,
    textAlign: "left",
    color: Color.colorBlack,
    fontFamily: FontFamily.openSansHebrew,
    left: 0,
    position: "absolute",
  },
  peopleBuy: {
    left: 290,
  },
  peopleBuyItem: {
    width: 61,
  },
  peopleBuy1: {
    left: 0,
  },
  productLaserItem2Child: {
    left: 145,
    width: 106,
    top: 0,
  },
  text25: {
    left: 172,
    color: Color.colorGoldenrod,
    fontSize: FontSize.size_base,
    position: "absolute",
  },
  textPosition5: {
    left: 130,
    color: Color.colorGoldenrod,
    top: 3,
    fontSize: FontSize.size_base,
    transform: [
      {
        rotate: "180deg",
      },
    ],
    fontFamily: FontFamily.fontAwesome6Pro,
    textAlign: "left",
    position: "absolute",
  },
  textPosition4: {
    left: 109,
    color: Color.colorGoldenrod,
    top: 3,
    fontSize: FontSize.size_base,
    transform: [
      {
        rotate: "180deg",
      },
    ],
    fontFamily: FontFamily.fontAwesome6Pro,
    textAlign: "left",
    position: "absolute",
  },
  text28: {
    width: 38,
    height: 28,
    textAlign: "right",
    fontWeight: "700",
    color: Color.gray,
    top: 0,
    fontFamily: FontFamily.openSansHebrew,
  },
  text29: {
    width: 82,
    top: 2,
    fontSize: FontSize.size_base,
    color: Color.gray,
    fontFamily: FontFamily.openSansHebrew,
    left: 0,
    position: "absolute",
  },
  text30: {
    color: Color.colorGoldenrod,
    top: 3,
    transform: [
      {
        rotate: "180deg",
      },
    ],
    fontFamily: FontFamily.fontAwesome6Pro,
    textAlign: "left",
  },
  stars: {
    width: 231,
    top: 224,
    height: 30,
    left: 0,
  },
  productLaserItem2: {
    left: 1,
    width: 251,
    top: 55,
  },
  image10Icon: {
    top: 80,
    width: 105,
    height: 181,
  },
  productLaserItem1Child: {
    borderRadius: Border.br_11xl,
    width: 265,
    top: 0,
    left: 0,
  },
  text31: {
    left: 172,
    color: Color.colorGoldenrod,
    fontSize: FontSize.size_base,
    position: "absolute",
  },
  text32: {
    left: 151,
    fontSize: FontSize.size_base,
    position: "absolute",
  },
  text37: {
    color: Color.colorGoldenrod,
    top: 3,
    transform: [
      {
        rotate: "180deg",
      },
    ],
    fontFamily: FontFamily.fontAwesome6Pro,
    textAlign: "left",
  },
  stars1: {
    left: 14,
    width: 231,
    top: 224,
    height: 30,
  },
  productLaserItem1: {
    left: 276,
    top: 55,
  },
  text38: {
    left: 250,
    top: 2,
  },
  arrowsChild: {
    left: 0,
    position: "absolute",
  },
  arrowsItem: {
    width: 30,
    height: 30,
    top: 0,
  },
  text41: {
    left: 11,
    color: Color.gray,
    fontSize: FontSize.size_sm,
    fontFamily: FontFamily.fontAwesome6Pro,
    textAlign: "left",
  },
  textPosition2: {
    left: 57,
    top: 8,
    color: Color.gray,
    fontSize: FontSize.size_sm,
    transform: [
      {
        rotate: "180deg",
      },
    ],
    fontFamily: FontFamily.fontAwesome6Pro,
    textAlign: "left",
    position: "absolute",
  },
  arrows: {
    left: 0,
  },
  parent: {
    left: 147,
    width: 395,
    top: 0,
  },
  image9Icon: {
    top: 78,
    left: 291,
    width: 236,
    height: 195,
    position: "absolute",
  },
  sales: {
    top: 0,
    left: 0,
  },
  salesWrapper: {
    top: 1026,
    left: -131,
  },
  bannerItem: {
    backgroundColor: "rgba(0, 0, 0, 0.4)",
  },
  bannerInner: {
    top: 24,
    width: 40,
    height: 40,
    left: 18,
    position: "absolute",
  },
  text43: {
    top: 22,
    left: 87,
    fontSize: FontSize.size_base,
    color: Color.colorWhite,
    position: "absolute",
  },
  text44: {
    top: 41,
    left: 68,
    fontWeight: "700",
    fontSize: FontSize.size_base,
    color: Color.colorWhite,
    position: "absolute",
  },
  text45: {
    top: 35,
    color: Color.pink,
    fontFamily: FontFamily.fontAwesome6Pro,
    fontSize: FontSize.size_lg,
    textAlign: "left",
  },
  banner: {
    top: 909,
    height: 87,
    width: 395,
    left: 15,
    position: "absolute",
  },
  arrows1: {
    left: 66,
  },
  text48: {
    top: 1,
    left: 316,
  },
  maskGroupIcon: {
    width: 147,
    left: 0,
  },
  productItemChild: {
    left: 10,
  },
  text51: {
    left: 18,
    textAlign: "right",
    fontFamily: FontFamily.openSansHebrew,
    fontSize: FontSize.size_sm,
    color: Color.colorWhite,
  },
  text52: {
    left: 40,
  },
  productItem: {
    width: 147,
    left: 314,
  },
  text53: {
    left: 41,
  },
  productItem1: {
    left: 152,
    width: 147,
  },
  maskGroupIcon2: {
    width: 71,
    left: 66,
  },
  text55: {
    left: 92,
  },
  productItemInner: {
    left: 0,
  },
  text56: {
    left: 8,
    textAlign: "right",
    fontFamily: FontFamily.openSansHebrew,
    fontSize: FontSize.size_sm,
    color: Color.colorWhite,
  },
  productItem2: {
    width: 137,
    left: 0,
  },
  discounts: {
    top: 664,
    left: -51,
    width: 461,
    height: 215,
    position: "absolute",
  },
  item005Child: {
    height: 164,
    width: 190,
    position: "absolute",
  },
  text57: {
    top: 12,
    width: 64,
    height: 39,
    fontSize: FontSize.size_sm,
  },
  text58: {
    top: 34,
    width: 70,
    height: 45,
    fontWeight: "700",
    fontSize: FontSize.size_base,
  },
  pngwing1Icon: {
    left: 7,
    width: 110,
    height: 159,
  },
  item005Item: {
    top: 85,
    width: 59,
    height: 58,
  },
  text59: {
    marginLeft: 35.43,
    lineHeight: 15,
    fontWeight: "100",
    textAlign: "center",
    width: 24,
    height: 15,
    left: "50%",
    color: Color.pink,
    fontFamily: FontFamily.fontAwesome6Pro,
    fontSize: FontSize.size_lg,
  },
  text60: {
    top: 98,
    right: 27,
    fontSize: 10,
    height: 14,
    width: 42,
    textAlign: "right",
    color: Color.gray,
    fontFamily: FontFamily.openSansHebrew,
    position: "absolute",
  },
  item005: {
    top: 266,
    left: 0,
  },
  item003Child: {
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: Color.colorWhite,
    borderStyle: "solid",
    borderRadius: Border.br_xl,
    shadowColor: "rgba(0, 0, 0, 0.1)",
    shadowOpacity: 1,
    elevation: 10,
    shadowRadius: 10,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    top: 0,
    left: 0,
  },
  text61: {
    top: 25,
    width: 115,
    height: 26,
    right: 13,
    textAlign: "right",
    fontWeight: "700",
    color: Color.gray,
    fontSize: FontSize.size_lg,
    fontFamily: FontFamily.openSansHebrew,
    position: "absolute",
  },
  text62: {
    width: 93,
    right: 13,
    height: 20,
  },
  item003Item: {
    top: 0,
    left: 0,
  },
  image21Icon: {
    top: 53,
    width: 122,
    height: 132,
    left: 0,
    position: "absolute",
  },
  image19Icon: {
    left: 77,
  },
  image15Icon: {
    left: 119,
    width: 69,
    height: 69,
    top: 47,
    position: "absolute",
  },
  image17Icon: {
    left: 9,
  },
  image18Icon: {
    left: 42,
  },
  image20Icon: {
    top: 105,
    left: 103,
    width: 78,
    height: 78,
    position: "absolute",
  },
  images: {
    top: 65,
    width: 188,
    height: 185,
    left: 0,
    position: "absolute",
  },
  item003: {
    top: 179,
    left: 205,
  },
  item002Child: {
    height: 164,
    width: 190,
    position: "absolute",
  },
  item002Item: {
    top: 51,
    width: 108,
    height: 108,
  },
  image14Icon: {
    top: 28,
    left: 6,
    width: 172,
    height: 134,
    position: "absolute",
  },
  text63: {
    right: 16,
    width: 61,
  },
  text64: {
    right: 15,
    width: 112,
    position: "absolute",
  },
  item002: {
    left: 205,
    top: 0,
  },
  item001Child: {
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: Color.colorWhite,
    borderStyle: "solid",
    borderRadius: Border.br_xl,
    shadowColor: "rgba(0, 0, 0, 0.1)",
    shadowOpacity: 1,
    elevation: 10,
    shadowRadius: 10,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    top: 0,
    left: 0,
  },
  item001Item: {
    left: 21,
    height: 150,
    top: 92,
  },
  inmodeEmbracerfRadioFrequenIcon: {
    top: 49,
    left: 3,
    width: 185,
    height: 200,
    position: "absolute",
  },
  text65: {
    top: 26,
    height: 26,
    textAlign: "right",
    fontWeight: "700",
    color: Color.gray,
    fontSize: FontSize.size_lg,
    fontFamily: FontFamily.openSansHebrew,
    right: 16,
  },
  text66: {
    right: 17,
    width: 77,
  },
  menu: {
    top: 204,
    height: 430,
    width: 395,
    left: 15,
    position: "absolute",
  },
  searchChild: {
    shadowRadius: 4,
    elevation: 4,
    shadowColor: "rgba(0, 0, 0, 0.1)",
    width: 394,
    borderRadius: Border.br_11xl,
    shadowOpacity: 1,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    backgroundColor: Color.colorWhite,
    top: 0,
    left: 0,
  },
  text67: {
    top: 16,
    left: 357,
    color: Color.pink,
    fontFamily: FontFamily.fontAwesome6Pro,
    fontWeight: "300",
    fontSize: FontSize.size_lg,
    textAlign: "left",
    position: "absolute",
  },
  text68: {
    left: 144,
    color: "#979797",
    width: 200,
    top: 14,
    fontSize: FontSize.size_base,
    fontFamily: FontFamily.openSansHebrew,
    position: "absolute",
  },
  search: {
    top: 129,
    left: 16,
  },
  profilePhotoHeader: {
    left: 17,
    width: 43,
    height: 43,
  },
  text69: {
    top: 66,
    left: 187,
    fontWeight: "700",
    color: Color.gray,
    fontSize: FontSize.size_lg,
    textAlign: "left",
    fontFamily: FontFamily.openSansHebrew,
    position: "absolute",
  },
  text70: {
    top: 92,
    fontSize: FontSize.size_base,
    color: Color.gray,
    textAlign: "left",
    fontFamily: FontFamily.openSansHebrew,
  },
  text71: {
    fontSize: 24,
    left: 314,
    top: 3,
    color: Color.gray,
    fontFamily: FontFamily.fontAwesome6Pro,
    textAlign: "left",
    position: "absolute",
  },
  text72: {
    left: 2,
    fontSize: 20,
    color: Color.gray,
    fontFamily: FontFamily.fontAwesome6Pro,
    fontWeight: "300",
    textAlign: "left",
  },
  logo1Icon: {
    marginLeft: -71.5,
    width: 85,
    left: "50%",
    top: 0,
  },
  notificationIcon: {
    top: 6,
    width: 8,
    height: 8,
    left: 0,
    position: "absolute",
  },
  header: {
    left: 75,
    width: 335,
    top: 14,
  },
  homeScreen: {
    backgroundColor: "#f0f1f3",
    flex: 1,
    width: "100%",
    height: 1979,
    overflow: "hidden",
  },
});

export default HomeScreen;
